import Pkg
Pkg.activate(".")

using Flutes

function floats(var)
  return mapvariable(x->parse(Float64, x), var)
end

function tones(var)
  return mapvariable(tone, var)
end

# input env vars
scale = tones("FLUTE_SCALE")
mind = floats("FLUTE_MIN_DIAMETERS")
maxd = floats("FLUTE_MAX_DIAMETERS")
minp = floats("FLUTE_MIN_PADDING")
maxp = floats("FLUTE_MAX_PADDING")
brk = parse(Int, readvariable("FLUTE_BREAK"))

flute = createflute(scale[end])
for h in 1:length(scale)-1
  # constrain hole diameters & positions
  addtonehole!(flute, scale[h]; ğ‘‘â‚‹=mind[h], ğ‘‘â‚Š=maxd[h], ğ‘â‚‹=minp[h], ğ‘â‚Š=maxp[h])
end
# find best fit
# all the magic happens here
diameters = optimal(flute)
# end magic

# break holes by foot/body
foot_diameters = []
foot_positions = []
body_diameters = []
body_positions = []
ğ›¥â„“ = 0.0 # closed-hole correction
â„“â‚œ = flutelength(flute.ğ‘“)
for h in 1:length(diameters)
  ğ‘“â‚• = flute.holes[h].ğ‘“
  ğ‘‘â‚• = diameters[h]
  â„“â‚• = toneholelength(ğ‘“â‚•; ğ‘‘=ğ‘‘â‚•) - ğ›¥â„“
  if h <= brk
    push!(body_diameters, ğ‘‘â‚•)
    push!(body_positions, â„“â‚•)
  else
    push!(foot_diameters, ğ‘‘â‚•)
    push!(foot_positions, â„“â‚•)
  end
  global ğ›¥â„“ += closedholecorrection(ğ‘“â‚•; ğ‘‘=ğ‘‘â‚•, â„“ğ‘Ÿ=â„“â‚œ-â„“â‚•)
end
flute_length = â„“â‚œ - ğ›¥â„“
tenon_length=26 # TODO: externalize constants
head_length=156

# place body/foot joint
spare = max((foot_positions[1] - body_positions[end] - tenon_length)/2, 0)
nofoot = body_positions[end] + spare + tenon_length
body_length = round(nofoot - head_length; digits=3)
foot_length = round(flute_length - nofoot; digits=3)

# export parameters to opencad json
params = createscadparameters()
bodyset = "body.3mf.params"
setscadparameter!(params, bodyset, "BODY_LENGTH", body_length)
setscadparameter!(params, bodyset, "BODY_DIAMETERS", map(bd->round(bd; digits=3), body_diameters))
setscadparameter!(params, bodyset, "BODY_POSITIONS", map(bp->round(bp-head_length; digits=3), body_positions))
footset = "foot.3mf.params"
setscadparameter!(params, footset, "FOOT_LENGTH", foot_length)
setscadparameter!(params, footset, "FOOT_DIAMETERS", map(fd->round(fd, digits=3), foot_diameters))
setscadparameter!(params, footset, "FOOT_POSITIONS", map(fp->round(fp-nofoot; digits=3), foot_positions))
writescadparameters(params, ARGS[1])

